### ISSUE TITLE
Full website list not loading?

### ISSUE THREAD

**Issue by tpandoteth** [State-Channel-4/frontend#16]
Was going through the C4 app to post website of the day on social and noticed that no sites that were submitted from 8/8 and onward showed up on https://app.channel4.wtf/discover

Went through 30-40 sites, so that it probabilistically unlikely to not come across any of those sites after 8/8.

Not sure if there is an issue with those sites appearing?

**Comment by hackertron** [comment]
potential fix : https://github.com/State-Channel-4/frontend/pull/18 , gotta test.

**Comment by tpandoteth** [comment]
@hackertron update from 9/12 weekly call, please add any details or clarification I might have missed!


This issue is due to pagination logic. Currently, C4 loads the first 100 sites by date submitted in ascending order and randomizes that list. Once that list is complete, it loads the next 100 sites. 

Because of that logic, it's uncommon for the first 100 sites to be browsed in its entirety, so the rest of the submitted sites are almost never viewed. 

In the future, this logic should change to either:
- Fetching a larger number of websites to randomize, eg: 1000
- Selecting a random website from the existing list of sites and remove that website from the 'next website' logic

**Comment by tpandoteth** [comment]
From 9/19 weekly meeting

New logic proposed by @hackertron: 
- Randomize page that will be loaded for user, eg: Page 1, 2, 3, etc.
- Will show sites for that page
- Randomly select new page and sites for that

TPan feedback on this: This works well for new users and if there are a lot of pages, but I'm concerned about what this would look like for returning users with a small number of pages/sites submitted. 

Not sure if there is better logic to implement that is still lightweight on the dev side?

**Comment by hackertron** [comment]
https://github.com/State-Channel-4/backend/pull/19
