### ISSUE TITLE
User profiles mixed up

### ISSUE THREAD

**Issue by hackertron** [State-Channel-4/frontend#19]
On 9/10, I noticed that my profile data was zeroed out. 

![Image](https://user-images.githubusercontent.com/140790116/267410075-d4ec50c1-fb3e-4355-9ff2-824017f4d8a1.png)

This didn't make sense because I didn't create a new account and have been logged in (entering my private key) 

This is the wallet address I've used for C4 for a while now (at least the past couple months). 

**Old/Original Wallet**

_id
64948a84e94455014d7b7400
walletAddress
"0x1203A243E45Bd46445A8489CBcc5aefC5bfCA06D"

createdAt
2023-06-22T17:53:08.356+00:00
updatedAt
2023-06-22T17:53:08.357+00:00

**The new wallet address created is this:**

_id
64fe9b5763865877b2f4ca0b
walletAddress
"0x6bA431D0a4B62e2aE1D772c9eB5F15B675605E4c"
createdAt
2023-09-11T04:45:11.256+00:00
updatedAt
2023-09-11T04:45:11.256+00:00

I submitted a couple of websites earlier today to see where the submission was coming from:

_id
6500995663865877b2f4cc34
title
"Positive News"
url
"https://www.positive.news/"
submittedBy
64948a84e94455014d7b7400
createdAt
2023-09-12T17:01:10.463+00:00
updatedAt
2023-09-12T17:01:10.463+00:00

Note the submittedBy objectID: **64948a84e94455014d7b7400**, which is the original wallet, but I am logged in as the new wallet.

**Comment by hackertron** [comment]
the issue occured after refactor and a small spelling mistake :( , so in routes earlier it was 
```router.get("/user/:id", authenticate, cc.get_specific_user);```  https://github.com/State-Channel-4/backend/blob/139625175dd5fb220e77dce3e71d8adab0eaec5c/routes/contracts.js#L65
now it's 
```router.get("/users/:id", authenticate, userControl.getUser);``` 

so the fix can be either update the request on the frontend or change it back in the backend. any works.

**Comment by thebeyondr** [comment]
> the issue occured after refactor and a small spelling mistake :( [...]

Figured it was something like this. I forgot to mention that I think route handlers should be plural. (users, tags, urls etc.) So routes would look like —

```js
/users/new
/users/:id 
/tags
/tags/new
[...]
```
— on the backend
